version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: dpds
       MYSQL_USER: user
       MYSQL_PASSWORD: password

   dpds:
     depends_on:
       - db
     build: ..
     ports:
       - "8080:80"
     restart: always
     environment:
       DATABASE_URL: mysql+mysqldb://user:password@db/dpds?charset=utf8mb4
       DPAYD_HTTP_URL: https://api.dpays.io
       DPDS_LOG_LEVEL: DEBUG

volumes:
    db_data:
